const stays = [
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-2/original/5161ff40-7ae2-4798-a9c2-5eea7647e2d8.png",
    itemId: "69b2fb9f-dd64-41a6-b34b-3233a22a91ae",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJvSFURkIayUwReGofaz4cufs",
      query: "Downtown Montreal",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "For sights like Notre-Dame Basilica of Montreal",
    subtitleA11yText: null,
    title: "Downtown Montreal, Quebec",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/3963ed21-1431-400f-a21c-88686f279fc4.png",
    itemId: "a381ff60-99c7-40ed-85a1-421329726b71",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJuU2C7F5E04kRiKK9VmHF0kY",
      query: "Niagara Falls",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "For nature-lovers",
    subtitleA11yText: null,
    title: "Niagara Falls, Ontario",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/519b9c37-d174-48b8-b065-4fde2bc70d88.png",
    itemId: "e205adc6-e230-4590-a71a-0f203f6baadf",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJrxNRX7IFzkwR7RXdMeFRaoo",
      query: "Ottawa",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "For sights like Parliament Hill",
    subtitleA11yText: null,
    title: "Ottawa, Ontario",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-2/original/fa576fb6-4fec-4784-b5da-7b3a5e43ac31.png",
    itemId: "457102f7-af52-404b-98e8-4fe6a7525c44",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJs0-pQ_FzhlQRi_OBm-qWkbs",
      query: "Vancouver",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "For its top-notch dining",
    subtitleA11yText: null,
    title: "Vancouver, British Columbia",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/2a08b260-09ac-40f4-9580-7d418cd0bb2f.png",
    itemId: "3a71a434-1608-4a4c-b666-b2962bcf464b",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJj3feJ2yYLIgRIQ7f2Fbuais",
      query: "Hamilton",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "Near you",
    subtitleA11yText: null,
    title: "Hamilton, Ontario",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/98e261a1-9acc-4c4f-bdd7-6163f574e708.png",
    itemId: "cc22b019-b5ef-4e7f-8035-42758a785e46",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJ1T-EnwNwcVMROrZStrE7bSY",
      query: "Calgary",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "For nature-lovers",
    subtitleA11yText: null,
    title: "Calgary, Alberta",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/2a08b260-09ac-40f4-9580-7d418cd0bb2f.png",
    itemId: "f47d57a4-b32f-4088-bfc6-220d2cac22ec",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJtwVr559GK4gR22ZZ175sFAM",
      query: "Mississauga",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "Popular with travellers near you",
    subtitleA11yText: null,
    title: "Mississauga, Ontario",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/c9333e22-1d8d-4d6c-80db-615f4c2d4cc4.png",
    itemId: "c8ae79fb-ad3d-4dc6-bbc6-5055df581ae5",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJk4jbBYqWuEwRAzro8GMtxY8",
      query: "Québec City",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "For sights like Château Frontenac",
    subtitleA11yText: null,
    title: "Québec City, Quebec",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/95f61d8c-910e-4016-abdb-71135e7d5fed.png",
    itemId: "6f6a0d02-040f-495c-91b3-b6a09cf39441",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJwfrbBxQhWksR3C2LQ6bja2Y",
      query: "Halifax",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "Popular with travellers near you",
    subtitleA11yText: null,
    title: "Halifax, Nova Scotia",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/b5648dad-1d76-43e4-9bbd-18ebce84ab7f.png",
    itemId: "1bf17075-9237-4369-984b-2e80cc30de0e",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJC5uNqA7yLogRlWsFmmnXxyg",
      query: "London",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "Popular with travellers near you",
    subtitleA11yText: null,
    title: "London, Ontario",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/c64c663b-11fb-419c-8c9d-3393d5406ffa.png",
    itemId: "49ba6eb4-75de-4594-b42b-dfb2da9286bb",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJv1rQpeoVK4gRd4bDfGYxLTU",
      query: "Brampton",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "Near you",
    subtitleA11yText: null,
    title: "Brampton, Ontario",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/3963ed21-1431-400f-a21c-88686f279fc4.png",
    itemId: "1ae628e0-4336-447d-bdc8-8cbb18169b91",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJESsa-ftz6lIRZMq5xvoaKis",
      query: "Winnipeg",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "Popular with travellers near you",
    subtitleA11yText: null,
    title: "Winnipeg, Manitoba",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/a1684b0b-ec5c-4193-b67b-7388aea59629.png",
    itemId: "22d8dbdc-ea31-473d-b627-7d45056f7e73",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJYZRP-6kLLU0RJjVq5LBwLjs",
      query: "Tobermory",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "A hidden gem",
    subtitleA11yText: null,
    title: "Tobermory, Ontario",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-2/original/5b9968b7-ad38-46e6-9577-2a3554758c6d.png",
    itemId: "e1722210-0b0d-47cd-8f17-f9725dd164a2",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJOwg_06VPwokRYv534QaPC8g",
      query: "New York City",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "For sights like Central Park",
    subtitleA11yText: null,
    title: "New York City, United States",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/61547cde-42ca-44bc-8c40-f1fd9aa0079e.png",
    itemId: "8a0ad855-909f-4207-8155-b4fe61597998",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJsQIX2RRf04kRwKIRfVRRAXY",
      query: "Niagara-on-the-Lake",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "Great for a weekend getaway",
    subtitleA11yText: null,
    title: "Niagara-on-the-Lake, Ontario",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-2/original/eb63c43e-fd0e-48f2-8cab-ef156da3bc0c.png",
    itemId: "f31b75c4-76fa-4528-85fb-2844a7a9910f",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJD7fiBh9u5kcRYJSMaMOCCwQ",
      query: "Paris",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "For its bustling nightlife",
    subtitleA11yText: null,
    title: "Paris, France",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/1f9cf4a3-3653-4a28-992d-efcbbf5fd2ba.png",
    itemId: "3243ebfc-974d-4474-b4cf-7211b4201a1f",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJF1KUvA12z0wRwFRNrq0MBAU",
      query: "Mont-Tremblant",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "Popular lake destination",
    subtitleA11yText: null,
    title: "Mont-Tremblant, Quebec",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/0c0f7ddf-6d44-4ed8-8190-35d4b6d08322.png",
    itemId: "5f2b69d4-c853-4538-90a8-9c2cc6d23f12",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJ5TpY6tt7KogRIKeLM-hhvtk",
      query: "Collingwood",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "Known for its skiing",
    subtitleA11yText: null,
    title: "Collingwood, Ontario",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/99437893-7e64-49e5-bf62-8ae72a3d0321.png",
    itemId: "2eff9862-e48e-4ce8-95ae-1e8b7d7b4a8f",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJbSDXGjejKogRWlNLqAAPLh0",
      query: "Barrie",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "Near you",
    subtitleA11yText: null,
    title: "Barrie, Ontario",
  },
  {
    __typename: "LocationSuggestionItem",
    iconUrl:
      "https://a0.muscache.com/im/pictures/airbnb-platform-assets/AirbnbPlatformAssets-hawaii-autosuggest-destination-icons-1/original/80daa7d3-4f45-4b30-967b-b220036d4a0c.png",
    itemId: "fc6c261f-8bd7-4e4d-95a1-1c49185d9e3d",
    location: null,
    searchParams: {
      __typename: "ExploreSearchParams",
      locationSearch: null,
      params: null,
      placeId: "ChIJ148i75TsKk0RFkl4t3anc0w",
      query: "Muskoka Lakes",
      refinementPaths: ["/homes"],
      resetFilters: false,
      resetKeys: [
        "parent_city_place_id",
        "place_id",
        "query",
        "location",
        "location_search",
        "ne_lat",
        "ne_lng",
        "sw_lat",
        "sw_lng",
        "search_by_map",
      ],
      tabId: null,
    },
    subtitle: "Great for a weekend getaway",
    subtitleA11yText: null,
    title: "Muskoka Lakes, Ontario",
  },
];

export default stays;
